# Pytorch

In [69]:
import torch

In [70]:
tensor0D = torch.tensor(1)
tensor0D.dtype

torch.int64

In [71]:
tensor1D = torch.tensor([1,2,3])
tensor1D.dtype

torch.int64

In [72]:
tensor2D = torch.tensor([[1,2,3],[4,5,6]])
tensor2D.dtype
b = tensor2D.shape
print(b)
c = tensor2D.reshape(3,2)
print(c)

torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [73]:
tensor3D = torch.tensor([[1,2],[3,4],[5,6]])
tensor3D.dtype
prec = tensor3D.to(torch.float16)
prec.dtype
a = tensor3D.shape
print(a)
tensor3D.view

torch.Size([3, 2])


<function Tensor.view>

In [74]:
t3d = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t3d)
Transpose = t3d.T
print(Transpose)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [75]:
A = torch.tensor([[2,4,3],[7,4,9]])
B = torch.tensor([[5,6,7],[1,3,0]])
C= A.T
A.matmul(A.T)


tensor([[ 29,  57],
        [ 57, 146]])

In [76]:
import torch.nn.functional as F
from torch.autograd import grad
y =torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2],requires_grad = True)  #By default Pytorch destroys computational graph after calculating the gradient to free the memory
b1 = torch.tensor([0.0],requires_grad = True)
z = x1*w1 + b1
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a,y)

grad_L_w1 = grad(loss, w1, retain_graph=True)  
grad_L_b1 =grad(loss,b1,retain_graph=True) # if we set retain_graph = True , then we can reuse the graph

print(grad_L_b1)
print(grad_L_w1)


# Pytorch provides .backwords on the loss
# Pytorch will calculate the gradient of all the leaf nodes in the graph, which will be stored via tensors .grad


loss.backward()
print(w1.grad)
print(b1.grad)

(tensor([-0.0817]),)
(tensor([-0.0898]),)
tensor([-0.0898])
tensor([-0.0817])


In [77]:
import torch
class NeuralNetwork(torch.nn.Module):
    def __init__(self,num_input,num_output):
        super().__init__()


        self.layers = torch.nn.Sequential(
            torch.nn.Linear(num_input,30),
            torch.nn.ReLU(),
            torch.nn.Linear(30,20),
            torch.nn.ReLU(),

            torch.nn.Linear(20,num_output),
            
            
        )

    def forward(self,x):
        logits = self.layers(x)
        return logits

In [78]:
model = NeuralNetwork(50,3)
model

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)

In [79]:
num_params = sum(p.numel() for p in model.parameters () if p.requires_grad)
print('Total number of trainable parameters:',num_params)

Total number of trainable parameters: 2213


#Feed Forward or Fully Connected Layer
## A linear layer multiplies the inputs with a weight matrix and adds a bias vector 

In [81]:
print (model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [82]:
print(model.layers[0].weight.shape)
print(model.layers[0].bias)

torch.Size([30, 50])
Parameter containing:
tensor([-0.1250,  0.0513,  0.0366,  0.0075,  0.0509,  0.0545, -0.0393,  0.0924,
        -0.1412, -0.1232, -0.1063,  0.0081, -0.1249,  0.0101, -0.0019, -0.1298,
         0.1388, -0.0330,  0.1017,  0.1247, -0.0554, -0.0417,  0.1388,  0.0159,
         0.1215,  0.0385,  0.0769, -0.1224, -0.0279,  0.0991],
       requires_grad=True)


If we use above code on different computer, the numers in matrix shown above will differ because the model weights are initialized with small random numbers, which are differnt each time we instantiate the network.
In DL, initializing small model weights with small random numbers is desired to break symmetry during training. 

Therefore, we use random seed by using torch.manual_seed()

In [84]:

torch.manual_seed(123)

model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [85]:
torch.manual_seed(123)
X= torch.rand((1,50))
out = model(X)
out

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)

In [86]:
with torch.no_grad():
    out= model(X)

print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [87]:
with torch.no_grad():
    out = torch.softmax(model(X),dim = 1)

print(out)

tensor([[0.3113, 0.3934, 0.2952]])


# Setting up efficient data loaders

In [89]:

#1. Creating custom dataset of five training examples with two features each.

X_train = torch.tensor([
    [-1.2 , 3.1],
    [-0.9 , 2.9],
    [-0.5 , 2.6],
    [2.3 , -1.1],
    [2.7 , -1.5]
])

#2. Accompanying the X_tX_train we crate a tensor containing the corresponding 
#   class labels: 3 belong to class 0 and 2 belongs to class 1 

y_train = torch.tensor([0, 0, 0, 1, 1])

#3. Make a test set consisting two entries

X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6]
])

y_test = torch.tensor([0,1])



In [90]:
#4. We create a custom ToyDataset class by subclassing from PyTorch's Dataset parent class

from torch.utils.data import Dataset
class ToyDataset(Dataset):
    def __init__(self,X,y):
        self.features = X
        self.labels = y

    def __getitem__(self,index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x,one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train,y_train)
test_ds = ToyDataset(X_test,y_test)


In [91]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
        dataset = train_ds,
        batch_size = 2,
        shuffle = False,
        num_workers = 0
)


test_ds = ToyDataset (X_test,y_test)

test_loader = DataLoader(
        dataset = test_ds,
        batch_size = 2,
        shuffle = False,
        num_workers =0
    
)

In [92]:
for idx, (x,y) in enumerate(train_loader):
    print(f"Batch {idx +1}:", x,y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.9000,  2.9000]]) tensor([0, 0])
Batch 2: tensor([[-0.5000,  2.6000],
        [ 2.3000, -1.1000]]) tensor([0, 1])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [93]:
train_loader = DataLoader(
    dataset= train_ds,
    batch_size= 2,
    shuffle= True,
    num_workers= 0,
    drop_last = True
    
)

for idx, (x,y) in enumerate(train_loader):
    print(f"Batch {idx +1 }:", x, y)

Batch 1: tensor([[ 2.7000, -1.5000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-1.2000,  3.1000]]) tensor([1, 0])


## Training Loop

In [121]:

#Duplicate


import torch
class NeuralNetwork(torch.nn.Module):
    def __init__(self,num_input,num_output):
        super().__init__()


        self.layers = torch.nn.Sequential(
            torch.nn.Linear(num_input,30),
            torch.nn.ReLU(),
            torch.nn.Linear(30,20),
            torch.nn.ReLU(),

            torch.nn.Linear(20,num_output),
            
            
        )

    def forward(self,x):
        logits = self.layers(x)
        return logits

In [123]:

import torch.nn.functional as F 

torch.manual_seed(123)
model = NeuralNetwork(num_input=2, num_output=2)
optimizer = torch.optim.SGD(model.parameters() , lr = 0.5)


num_epoch = 3

for epoch in range(num_epoch):
    model.train()
    for batch_idx , (features, labels) in enumerate (train_loader):
        logits = model(features)

        loss = F.cross_entropy(logits , labels) 

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f"Epoch:  {epoch +1:03d}/{num_epoch:03d}" 
              f"| Batch {batch_idx:03d}/{len(train_loader):03d}" 
              f" | Train/Val Loss:  {loss : .2f}"  )

    model.eval()

Epoch:  001/003| Batch 000/002 | Train/Val Loss:   0.75
Epoch:  001/003| Batch 001/002 | Train/Val Loss:   0.65
Epoch:  002/003| Batch 000/002 | Train/Val Loss:   0.44
Epoch:  002/003| Batch 001/002 | Train/Val Loss:   0.13
Epoch:  003/003| Batch 000/002 | Train/Val Loss:   0.03
Epoch:  003/003| Batch 001/002 | Train/Val Loss:   0.00


In [125]:
# Prediction

with torch.no_grad():
    outputs = model(X_train)

outputs

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])

In [129]:
# To obtain the class membership probabilities we can use

torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim= 1)
print(probas)

tensor([[    0.9991,     0.0009],
        [    0.9982,     0.0018],
        [    0.9949,     0.0051],
        [    0.0491,     0.9509],
        [    0.0307,     0.9693]])


In [131]:
predictions = torch.argmax(probas, dim = 1) # we can directly apply outputs instead of probas
predictions

tensor([0, 0, 0, 1, 1])

In [139]:
# Verification

predictions == y_train

tensor([True, True, True, True, True])

In [141]:
# To calculate number of currect prediction

torch.sum(predictions == y_train)

tensor(5)

In [145]:
#To generalize prediction accuracy 


def compute_accuracy (model,dataloader):
    model = model.eval()
    correct = 0.0
    total_examples = 0

    for  idx , (features, labels) in enumerate (dataloader):

        with torch.no_grad():
            logits = model (features)

        predictions = torch.argmax(logits, dim =1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct/total_examples).item()



In [147]:
compute_accuracy (model , train_loader)

1.0

In [149]:
compute_accuracy (model, test_loader)

1.0

# Saving and Loading Model

In [151]:
torch.save(model.state_dict(),'model.pth')

In [153]:
model = NeuralNetwork (2,2)
model.load_state_dict(torch.load("model.pth", weights_only = True))

<All keys matched successfully>

# Optimizing using GPU

In [155]:
print(torch.cuda.is_available())

False
